var records = [
  "http://www.w3.org|W3C|Организация, занимающаяся разработкой стандартов WWW.",
  "https://www.ietf.org|IETF|Международная организация, выпускающая RFC по протоколам Интернета.",
  "https://www.rfc-editor.org|RFC Editor|Архив RFC-документов (HTTP, FTP и другие).",
  "https://developer.mozilla.org|MDN Web Docs|Документация по HTML, CSS, JavaScript и веб-API.",
  "https://whatwg.org|WHATWG|Рабочая группа по развитию HTML Living Standard.",
  "https://www.w3schools.com|W3Schools|Учебник по веб-технологиям: HTML, CSS, JS.",
  "https://www.apache.org|Apache|Сайт популярного веб-сервера Apache.",
  "https://nginx.org|Nginx|Сайт сервера Nginx (HTTP, реверс-прокси).",
  "https://www.iana.org|IANA|Управление портами и протоколами Интернета.",
  "https://httpd.apache.org/docs|Apache HTTPD Docs|Документация по Apache HTTP Server.",
  "https://developer.chrome.com|Chrome Developers|Ресурсы по движку Blink и браузеру Chrome.",
  "https://www.mozilla.org/firefox|Firefox|Сайт браузера Mozilla Firefox.",
  "https://www.opera.com|Opera|Сайт браузера Opera.",
  "https://www.microsoft.com/edge|Microsoft Edge|Сайт браузера Microsoft Edge.",
  "https://www.filezilla-project.org|FileZilla|Популярный FTP-клиент.",
  "https://winscp.net|WinSCP|FTP/SFTP клиент WinSCP для Windows.",
  "https://curl.se|cURL|Инструмент командной строки для HTTP и FTP.",
  "https://ftp.gnu.org|GNU FTP|FTP-архив проектов GNU.",
  "https://www.vsftpd.beasts.org|vsftpd|Безопасный FTP-сервер.",
  "https://proftpd.org|ProFTPD|Гибкий FTP-сервер.",
  "https://www.ietf.org/rfc/rfc959.txt|RFC 959|Спецификация протокола FTP.",
  "https://www.ietf.org/rfc/rfc2616.txt|RFC 2616|Спецификация HTTP/1.1.",
  "https://datatracker.ietf.org/doc/html/rfc9110|RFC 9110|Актуальный стандарт HTTP/1.1.",
  "https://www.ietf.org/rfc/rfc7230.txt|RFC 7230|HTTP/1.1 Message Syntax and Routing.",
  "https://www.iana.org/assignments/ftp-commands-extensions/ftp-commands-extensions.xhtml|FTP Extensions|Список расширений FTP.",
  "https://http2.github.io|HTTP/2|Спецификация HTTP/2.",
  "https://http3-explained.haxx.se|HTTP/3 Explained|Учебные материалы по HTTP/3.",
  "https://tools.ietf.org/html/rfc1738|RFC 1738|Стандарт URL (Uniform Resource Locator).",
  "https://www.tcpipguide.com|TCP/IP Guide|Подробное руководство по протоколам TCP/IP, включая HTTP и FTP.",
  "https://developer.ibm.com/articles/|IBM Developers|Статьи IBM о веб-технологиях."
];
